# Étape 1 : Construire le projet avec Maven et Java 17
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2 : Lancer l'application avec Java 17 en limitant la mémoire
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080

# Limite mémoire (-Xmx300m) pour éviter crash sur Render gratuit
CMD ["java", "-Xmx300m", "-jar", "app.jar"]
